// Objective-C API for talking to metamask/sdk/go Go package.
//   gobind -lang=objc metamask/sdk/go
//
// File is generated by gobind. Do not edit.

#ifndef __Ecies_H__
#define __Ecies_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


// skipped function EciesDecrypt with unsupported parameter or return types


// skipped function EciesEncrypt with unsupported parameter or return types


// skipped function EciesGeneratePrivateKey with unsupported parameter or return types


// skipped function EciesGetPublicKey with unsupported parameter or return types


// skipped function FromCString with unsupported parameter or return types


// skipped function ToCString with unsupported parameter or return types


#endif
