// Objective-C API for talking to metamask/sdk/go Go package.
//   gobind -lang=objc metamask/sdk/go
//
// File is generated by gobind. Do not edit.

#ifndef __Ecies_H__
#define __Ecies_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


#endif
