
// Objective-C API for talking to the following Go packages
//
//	metamask/sdk/go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ecies_FRAMEWORK_H__
#define __Ecies_FRAMEWORK_H__

#include "Ecies.objc.h"
#include "Universe.objc.h"

#endif
