services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    command: redis-server --maxmemory 100mb --maxmemory-policy volatile-lru --loglevel debug
    ports:
      - "${DOCKER_ENV_LOCAL_REDIS_PORT:-6379}:6379"
