server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: label
          values: ["logging=promtail"]
  relabel_configs:
    - source_labels: ['__meta_docker_container_id']
      target_label: 'container_id'
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container_name'
    - source_labels: ['__meta_docker_container_label_service']
      target_label: 'service'
    - source_labels: ['__meta_docker_container_label_job']
      target_label: 'job'
    - source_labels: ['__meta_docker_container_label_env']
      target_label: 'env' 