name: Build, Deploy Test dapp

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            aws_region:
                required: true
                type: string
            aws_iam_role:
                required: true
                type: string
            build_name:
                required: true
                type: string
            build_path:
                type: string
                default: build
            s3_bucket:
                required: true
                type: string
            s3_prefix:
                required: false
                type: string
            url:
                required: true
                type: string

jobs:
    build-dapp:
        name: Build dapp
        runs-on: ubuntu-latest
        environment:
          name: ${{ inputs.environment }}
          url: ${{ inputs.url }}${{ inputs.s3_prefix }} 
        # build dapp job
        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js 20.20.2
            uses: actions/setup-node@v3
            with:
              node-version: '20.20.2'
              cache: yarn

          - name: Install dependencies
            run: yarn install
        
          - name: Build
            run: yarn build

          - name: Copy build
            run: cp -r build ${{ inputs.build_name }}

          - name: Upload build artifacts
            uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.build_name }}
              path: ${{ inputs.build_path }}

    deploy-dapp:
        name: Deploy dapp
        runs-on: ubuntu-latest
        needs: build-dapp
        steps:
          - name: Download build artifacts
            uses: actions/download-artifact@v3
            with:
              name: ${{ inputs.build_name }}
              path: ${{ inputs.build_name }}

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-region: ${{ inputs.aws_region }}
              role-to-assume: ${{ inputs.aws_iam_role }}
        
          - name: Deploy to S3
            run: |
              aws s3 cp ${{ inputs.build_name }} s3://${{ inputs.s3_bucket }}${{ inputs.s3_prefix }} --recursive --acl private --cache-control max-age=0
      
          - name: URL
            run: |
                if [[ -n "${{ inputs.s3_prefix }}" ]]; then
                  echo "Deployed with S3 prefix: ${{ inputs.s3_prefix }}"
                  echo "Build available at ${{ inputs.url }}${{ inputs.s3_prefix }}"
                else
                  echo "Build available at ${{ inputs.url }}"
                fi
            shell: bash

          - name: Comment on PR
            run: gh pr comment "${PR_NUMBER}" --body "Build available at ${{ inputs.url }}${{ inputs.s3_prefix }}"