name: Deploy to CDN

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository at tag
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    # Fetch deploy script from main instead of using the one in the tag
    - name: Fetch deploy script from main
      run: |
        git fetch origin main
        git checkout origin/main -- scripts/deploy-cdn.sh

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Yarn 3
      run: yarn set version 3.5.1

    - name: Install Dependencies
      run: yarn install --immutable

    - name: Run deploy CDN script
      env:
        tag: ${{ github.event.inputs.tag }}
      run: bash ./scripts/deploy-cdn.sh

    - name: Deploy dapps
      uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        # force_orphan: true  # removing for now as it is incompatible with keep_files
        keep_files: true  # Important to keep the rest of the files deployed previously
        publish_dir: ./deployments
